### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by maxnowack** [pushrocks/phoneserve#1]
I'm currently searching for a sipgate api implementation for nodejs and found this package, which looks very promising. Unfortunately there isn't any code in this repository.
Do you have already started working on this?

**Comment by philkunz** [comment]
@maxnowack Hi, yes I started this package since we need it ourselves. I did the basic implementation as shown in the readme in a private fork. I'll sync it about next week when it is 100% ready.

Little note: I'm closing issues here, because I moved my complete stack to gitlab:
https://gitlab.com/pushrocks/phoneserve
